language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo sh -c 'echo "deb http://deb.opera.com/opera/ stable non-free" >> /etc/apt/sources.list.d/opera.list'
- sudo sh -c 'wget -O - http://deb.opera.com/archive.key | apt-key add -'
- sudo sh -c 'wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key
  add -'
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
- sudo apt-get update
- sudo apt-get install opera
- sudo apt-get install google-chrome-stable
node_js:
- 0.1
deploy:
  provider: heroku
  app: angularjs-interpolate-interceptor
  strategy: git
  api_key:
    secure: ysEe080RjESX3rA+vFlbxBkw1nWmEDRygbesHXEWP5ccQvMMrpfcKYbD1VBc6aUWiheuChLkR4o8Vpt+EmU2zP+P1jyT+lhF4UsHQjGNwG+NtfgneiHeQs8bJNSDty7W9hwXrzZu+oS88ggMq7IL4ySinNCvsupVJxN+AfyZkWU=
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
